name: 'Hello World'
description: 'Rename a PR on open using a regex'
inputs:
  branch-regex: 
    description: 'Regex using named groups for formatting a PR title'
    required: true
  title-format: 
    description: 'String format using named groups to generate the PR title'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'